name: Checked Code
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Test
        run: deno test --allow-write --allow-read
      - name: Lint
        run: deno lint --unstable
      - name: Format Check
        run: deno fmt --check --ignore=README.md,README_JP.md,./.github/